# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Refrigerator', '0012_auto_20170520_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_image',
            field=models.ImageField(null=True, upload_to=b'Images/'),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='food_type',
            field=models.CharField(max_length=5),
        ),
    ]
