# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-24 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Refrigerator', '0019_auto_20170618_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='memo',
        ),
        migrations.RemoveField(
            model_name='memo',
            name='title',
        ),
        migrations.AddField(
            model_name='memo',
            name='author',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
